# Generated by Django 4.1.4 on 2023-01-13 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adotar', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedidoadocao',
            old_name='usuario',
            new_name='user',
        ),
    ]
